version: "3.3"
services:
  gitlog-per-package:
    build:
      dockerfile: packages/docker/gitlog-per-package/Dockerfile.debian
      context: ${PWD}
    image: pnpmkambrium/gitlog-per-package:latest
    tty: true
    stdin_open: true
    # optional : customize git log options
    #    environment:
    #      GIT_LOG_OPTIONS: "--stat --abbrev-commit"
    volumes:
      - type: bind
        source: ${PWD}
        target: /app
